#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src" / "js"
OUT_FILE = ROOT / "assets" / "js" / "archive.js"
MODULES = [
    "00-data-loaders.js",
    "01-taxonomies-filters.js",
    "02-sections-state-utils.js",
    "03-render-common.js",
    "04-navigation-routing.js",
    "05-catalog.js",
    "06-details.js",
    "07-events-render-init.js",
    "08-scrollbars-responsive.js",
]

HEADER = """/*
  Библиотека Лороведьмы — compiled script.
  Do not edit this file directly: edit src/js/*.js and run tools/build_js.py.
*/
"""


def read_module(name: str) -> str:
    path = SRC_DIR / name
    if not path.exists():
        raise FileNotFoundError(f"Missing JS module: {path}")
    return path.read_text(encoding="utf-8").strip()


def main() -> None:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    chunks = [HEADER.strip()]
    for name in MODULES:
        chunks.append(read_module(name))
    OUT_FILE.write_text("\n\n".join(chunks).strip() + "\n", encoding="utf-8", newline="\n")
    print(f"Built {OUT_FILE.relative_to(ROOT)} from {len(MODULES)} JS modules.")


if __name__ == "__main__":
    main()
