#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src" / "css"
OUT_FILE = ROOT / "assets" / "css" / "archive.css"
MODULES = [
    "00-tokens.css",
    "01-base.css",
    "02-layout.css",
    "03-navigation.css",
    "04-catalog.css",
    "05-reader.css",
    "06-entries.css",
    "07-responsive.css",
]

HEADER = """/*
  Библиотека Лороведьмы — compiled stylesheet.
  Do not edit this file directly: edit src/css/*.css and run tools/build_css.py.
*/
"""


def read_module(name: str) -> str:
    path = SRC_DIR / name
    if not path.exists():
        raise FileNotFoundError(f"Missing CSS module: {path}")
    return path.read_text(encoding="utf-8").strip()


def main() -> None:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    chunks = [HEADER.strip()]
    for name in MODULES:
        chunks.append(read_module(name))
    OUT_FILE.write_text("\n\n".join(chunks).strip() + "\n", encoding="utf-8")
    print(f"Built {OUT_FILE.relative_to(ROOT)} from {len(MODULES)} CSS modules.")


if __name__ == "__main__":
    main()
