#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src" / "js"
OUT_FILE = ROOT / "assets" / "js" / "archive.js"
MODULES = [
    "00-core/00-data-store.js",
    "00-core/01-taxonomies-and-filters.js",
    "00-core/02-section-config.js",
    "00-core/03-ui-state-and-dom.js",
    "00-core/04-text-and-scroll-utils.js",
    "01-render/00-common-renderers.js",
    "02-routing/00-navigation-and-router.js",
    "01-render/01-catalog-renderer.js",
    "01-render/02-detail-renderers.js",
    "03-app/00-event-handlers.js",
    "03-app/01-render-controller.js",
    "03-app/02-scrollbars-responsive.js",
]

HEADER = """/*
  Библиотека Лороведьмы — compiled script.
  Do not edit this file directly: edit src/js/** and run tools/build_js.py.
*/
"""


def read_module(name: str) -> str:
    path = SRC_DIR / name
    if not path.exists():
        raise FileNotFoundError(f"Missing JS module: {path}")
    return path.read_text(encoding="utf-8").strip()


def main() -> None:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    chunks = [HEADER.strip(), "(() => {", '  "use strict";']
    for name in MODULES:
        module = read_module(name)
        indented = "\n".join(f"  {line}" if line else "" for line in module.splitlines())
        chunks.append(f"  // src/js/{name}\n{indented}")
    chunks.append("})();")
    OUT_FILE.write_text("\n\n".join(chunks).strip() + "\n", encoding="utf-8", newline="\n")
    print(f"Built {OUT_FILE.relative_to(ROOT)} from {len(MODULES)} JS modules.")


if __name__ == "__main__":
    main()
