#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
ASSETS_DIR = ROOT / "assets"
SRC_CSS_DIR = ROOT / "src" / "css"
SRC_JS_DIR = ROOT / "src" / "js"
SECTIONS = ("books", "artifacts", "weapons", "items", "stories", "enemies")
LANGS = {"ru", "en", "zh"}

KNOWN_REGIONS = {
    "Мондштадт", "Ли Юэ", "Инадзума", "Сумеру", "Фонтейн", "Натлан",
    "Нод-Край", "Снежная", "Тейват", "Энканомия", "Разлом",
    "Подземные шахты Разлома", "Море древности", "Селестия", "Каэнри'ах",
    "Каэнри’ах", "Иной мир",
}
KNOWN_ITEM_GROUPS = {
    "weekly_bosses", "world_bosses", "common_enemies", "development_materials",
    "teyvat_resources", "serenitea_pot", "useful_items", "misc",
}
KNOWN_DEVELOPMENT_MATERIAL_TYPES = {
    "talents", "character_ascension", "weapon_ascension",
}
KNOWN_ITEM_TYPES = {
    "teyvat_resources": {"ore", "local_specialty", "plant", "animal", "craft", "ingredient"},
    "serenitea_pot": {"wood", "blueprint", "seed", "misc"},
    "useful_items": {"tool", "seelie", "equipment"},
    "misc": {"misc"},
}
KNOWN_WEAPON_TYPES = {"sword", "claymore", "bow", "catalyst", "polearm"}
KNOWN_BOOK_TYPES = {"book_series", "notes"}
KNOWN_ARTIFACT_PARTS = {"flower", "plume", "sands", "goblet", "circlet"}
KNOWN_ENEMY_GROUPS = {
    "hilichurls", "elementals", "fatui", "automatons", "human_factions",
    "abyss", "mystical_beasts",
}
KNOWN_ENEMY_TYPES = {"common_enemy", "world_boss", "weekly_boss", "boss"}
KNOWN_STORY_GROUPS = {"archon_quests", "legend_quests", "world_quests", "character_stories", "world_stories"}
KNOWN_STORY_ELEMENTS = {"pyro", "hydro", "anemo", "electro", "dendro", "cryo", "geo", "witchcraft", "lunar_reactions", "star_blade"}

CSS_MODULES = [
    "00-tokens.css",
    "01-base.css",
    "02-layout.css",
    "03-navigation.css",
    "04-catalog.css",
    "05-reader.css",
    "06-entries.css",
    "07-responsive.css",
]
CSS_HEADER = """/*
  Библиотека Лороведьмы — compiled stylesheet.
  Do not edit this file directly: edit src/css/*.css and run tools/build_css.py.
*/
"""
JS_MODULES = [
    "00-core/00-data-store.js",
    "00-core/01-taxonomies-and-filters.js",
    "00-core/02-section-config.js",
    "00-core/03-ui-state-and-dom.js",
    "00-core/04-text-and-scroll-utils.js",
    "01-render/00-common-renderers.js",
    "02-routing/00-navigation-and-router.js",
    "01-render/01-catalog-renderer.js",
    "01-render/02-detail-renderers.js",
    "03-app/00-event-handlers.js",
    "03-app/01-render-controller.js",
    "03-app/02-scrollbars-responsive.js",
]
JS_HEADER = """/*
  Библиотека Лороведьмы — compiled script.
  Do not edit this file directly: edit src/js/** and run tools/build_js.py.
*/
"""
CACHE_RE = re.compile(r"assets/(?:css/archive\.css|js/archive\.js|icons/(?:logo_icon_05|logo_menu_symbol)\.webp)\?v=([A-Za-z0-9_.-]+)")
TEXT_SUFFIXES = {
    ".css", ".html", ".js", ".json", ".md", ".py", ".txt", ".yml", ".yaml",
}
TEXT_NAMES = {".editorconfig", ".gitattributes", ".gitignore", ".gitkeep", ".nojekyll"}
SKIP_DIRS = {".git", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", "node_modules"}

errors: list[str] = []


def fail(message: str) -> None:
    errors.append(message)


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001 - this is a validation script.
        fail(f"{rel(path)}: не удалось прочитать JSON ({exc})")
        return None


def title_ru(item: dict[str, Any]) -> str:
    title = item.get("title")
    if isinstance(title, dict):
        return str(title.get("ru") or "").strip()
    return str(item.get("title_ru") or item.get("name") or "").strip()


def localized_text_present(container: dict[str, Any], key: str = "text") -> bool:
    value = container.get(key)
    if isinstance(value, dict):
        return any(str(value.get(lang) or "").strip() for lang in LANGS)
    return bool(str(value or "").strip())


def split_regions(value: Any) -> list[str]:
    if isinstance(value, list):
        source = value
    else:
        source = str(value or "").replace("，", ",").split(",")
    return [str(region).strip() for region in source if str(region).strip()]


def check_asset(path_value: Any, owner: str) -> None:
    path_text = str(path_value or "").strip()
    if not path_text:
        return
    if path_text.startswith(("http://", "https://", "data:")):
        return
    path = ROOT / path_text
    if not path.exists():
        fail(f"{owner}: не найден файл ассета {path_text}")


def check_languages(item: dict[str, Any], owner: str) -> None:
    languages = item.get("languages")
    if languages is None:
        return
    if not isinstance(languages, list):
        fail(f"{owner}: languages должен быть списком")
        return
    unknown = sorted(set(map(str, languages)) - LANGS)
    if unknown:
        fail(f"{owner}: неизвестные языки в languages: {', '.join(unknown)}")


def check_regions(item: dict[str, Any], owner: str) -> None:
    regions = split_regions(item.get("filter_regions") or item.get("region") or "")
    unknown = sorted(region for region in regions if region not in KNOWN_REGIONS)
    if unknown:
        fail(f"{owner}: неизвестные регионы: {', '.join(unknown)}")


def check_common_index_fields(item: dict[str, Any], owner: str, *, enemy: bool = False) -> None:
    for key in ("search_text", "sort_version", "filter_regions", "filter_type"):
        if key not in item:
            fail(f"{owner}: в индексной записи отсутствует служебное поле {key}")
    if enemy and "enemy_type_keys" not in item:
        fail(f"{owner}: в индексной записи врага отсутствует enemy_type_keys")


def load_indexes() -> dict[str, list[dict[str, Any]]]:
    indexes: dict[str, list[dict[str, Any]]] = {}
    for section in SECTIONS:
        path = DATA_DIR / f"{section}_index.json"
        data = read_json(path)
        if data is None:
            indexes[section] = []
            continue
        if not isinstance(data, list):
            fail(f"{rel(path)}: ожидается список")
            indexes[section] = []
            continue
        indexes[section] = [item for item in data if isinstance(item, dict)]
        if len(indexes[section]) != len(data):
            fail(f"{rel(path)}: все элементы должны быть объектами")
    return indexes


def detail_path(section: str, item_id: str) -> Path:
    return DATA_DIR / section / f"{item_id}.json"


def check_index_and_details(indexes: dict[str, list[dict[str, Any]]]) -> dict[str, dict[str, dict[str, Any]]]:
    details: dict[str, dict[str, dict[str, Any]]] = {section: {} for section in SECTIONS}

    all_global_ids: list[str] = []
    for section, items in indexes.items():
        ids = [str(item.get("id") or "").strip() for item in items]
        for empty_index, item_id in enumerate(ids, start=1):
            if not item_id:
                fail(f"data/{section}_index.json: пустой id в записи #{empty_index}")
        for item_id, count in Counter(ids).items():
            if item_id and count > 1:
                fail(f"data/{section}_index.json: дублирующийся id {item_id}")
        all_global_ids.extend(f"{section}:{item_id}" for item_id in ids if item_id)

        for item in items:
            item_id = str(item.get("id") or "").strip()
            if not item_id:
                continue
            owner = f"data/{section}_index.json#{item_id}"
            if not title_ru(item):
                fail(f"{owner}: пустое русское название")
            check_languages(item, owner)
            check_regions(item, owner)
            check_asset(item.get("icon"), owner)
            check_common_index_fields(item, owner, enemy=(section == "enemies"))
            if section == "stories" and len(str(item.get("search_text") or "")) > 1200:
                fail(f"{owner}: stories_index должен быть лёгким, без полного текста истории в search_text")

            path = detail_path(section, item_id)
            if not path.exists():
                fail(f"{owner}: нет detail-файла {rel(path)}")
                continue
            detail = read_json(path)
            if not isinstance(detail, dict):
                fail(f"{rel(path)}: detail-файл должен быть объектом")
                continue
            if str(detail.get("id") or "").strip() != item_id:
                fail(f"{rel(path)}: id detail-файла не совпадает с индексом")
            details[section][item_id] = detail

    for global_id, count in Counter(all_global_ids).items():
        if count > 1:
            fail(f"дублирующийся глобальный id {global_id}")

    return details


def check_story_search_index(indexes: dict[str, list[dict[str, Any]]]) -> None:
    path = DATA_DIR / "stories_search.json"
    story_ids = {str(item.get("id") or "") for item in indexes.get("stories", []) if item.get("id")}

    if not story_ids:
        return
    if not path.exists():
        fail("data/stories_search.json: отсутствует ленивый полнотекстовый индекс историй")
        return

    data = read_json(path)
    if not isinstance(data, list):
        fail("data/stories_search.json: индекс должен быть списком")
        return

    search_ids = {str(item.get("id") or "") for item in data if isinstance(item, dict) and item.get("id")}
    missing = sorted(story_ids - search_ids)
    extra = sorted(search_ids - story_ids)
    if missing:
        fail(f"data/stories_search.json: нет записей для {', '.join(missing[:10])}")
    if extra:
        fail(f"data/stories_search.json: лишние записи {', '.join(extra[:10])}")

    for item in data:
        if not isinstance(item, dict):
            fail("data/stories_search.json: каждая запись должна быть объектом")
            continue
        if not str(item.get("search_text") or "").strip():
            fail(f"data/stories_search.json#{item.get('id')}: пустой search_text")


def check_books(books: dict[str, dict[str, Any]]) -> None:
    for item_id, book in books.items():
        owner = f"data/books/{item_id}.json"
        book_type = str(book.get("subtype") or book.get("book_type") or "").strip()
        if book_type and book_type not in KNOWN_BOOK_TYPES:
            fail(f"{owner}: неизвестный тип книги {book_type}")
        volumes = book.get("volumes")
        if not isinstance(volumes, list) or not volumes:
            fail(f"{owner}: книга без частей/томов")
            continue
        declared = book.get("volume_count")
        if isinstance(declared, int) and declared != len(volumes):
            fail(f"{owner}: volume_count={declared}, но частей/томов {len(volumes)}")
        numbers = []
        for volume in volumes:
            if not isinstance(volume, dict):
                fail(f"{owner}: часть/том должен быть объектом")
                continue
            number = volume.get("number")
            numbers.append(number)
            if not localized_text_present(volume):
                fail(f"{owner}: часть/том {number or '?'} без текста")
        duplicates = [str(value) for value, count in Counter(numbers).items() if value is not None and count > 1]
        if duplicates:
            fail(f"{owner}: дублирующиеся номера частей/томов: {', '.join(duplicates)}")


def check_artifacts(artifacts: dict[str, dict[str, Any]]) -> None:
    for item_id, artifact in artifacts.items():
        owner = f"data/artifacts/{item_id}.json"
        parts = artifact.get("parts")
        if not isinstance(parts, list):
            fail(f"{owner}: parts должен быть списком")
            continue

        keys: list[str] = []
        for part in parts:
            if isinstance(part, dict):
                keys.append(str(part.get("key") or "").strip())

        duplicate_keys = sorted(key for key in set(keys) if key and keys.count(key) > 1)
        if duplicate_keys:
            fail(f"{owner}: дублирующиеся части артефакта: {', '.join(duplicate_keys)}")

        # Most artifact sets contain the classic five slots, but Genshin also has
        # one-piece artifacts such as the Prayers circlets.  The archive supports
        # both shapes; anything else is likely an incomplete entry.
        if len(keys) == 5:
            if set(keys) != KNOWN_ARTIFACT_PARTS:
                fail(f"{owner}: сет из 5 артефактов должен содержать части: {', '.join(sorted(KNOWN_ARTIFACT_PARTS))}")
        elif len(keys) == 1:
            if not keys[0]:
                fail(f"{owner}: одиночный артефакт должен иметь ключ части")
        else:
            fail(f"{owner}: артефакт должен содержать 1 или 5 частей, сейчас: {len(keys)}")

        for part in parts:
            if not isinstance(part, dict):
                fail(f"{owner}: часть артефакта должна быть объектом")
                continue
            key = str(part.get("key") or "").strip()
            if not localized_text_present(part):
                fail(f"{owner}: часть {key or '?'} без текста")
            check_asset(part.get("icon"), f"{owner}#{key}")


def check_weapons(weapons: dict[str, dict[str, Any]]) -> None:
    for item_id, weapon in weapons.items():
        owner = f"data/weapons/{item_id}.json"
        weapon_type = str(weapon.get("weapon_type") or weapon.get("type") or "").strip()
        if weapon_type not in KNOWN_WEAPON_TYPES:
            fail(f"{owner}: неизвестный тип оружия {weapon_type or 'пусто'}")
        rarity = weapon.get("rarity")
        if rarity is not None and str(rarity) not in {"1", "2", "3", "4", "5"}:
            fail(f"{owner}: неизвестная редкость оружия {rarity}")
        if not localized_text_present(weapon) and not localized_text_present(weapon, "description"):
            fail(f"{owner}: оружие без текста/описания")


def check_items(items: dict[str, dict[str, Any]], enemies: dict[str, dict[str, Any]]) -> None:
    enemy_ids = set(enemies)
    for item_id, item in items.items():
        owner = f"data/items/{item_id}.json"
        group = str(item.get("item_group") or "").strip()
        if group not in KNOWN_ITEM_GROUPS:
            fail(f"{owner}: неизвестная группа предмета {group or 'пусто'}")

        material_type = str(item.get("material_type") or "").strip()
        if group == "development_materials" and material_type not in KNOWN_DEVELOPMENT_MATERIAL_TYPES:
            fail(f"{owner}: неизвестный material_type {material_type or 'пусто'}")

        item_type = str(item.get("item_type") or "").strip()
        if item_type and item_type not in KNOWN_ITEM_TYPES.get(group, set()):
            fail(f"{owner}: неизвестный item_type {item_type} для группы {group}")

        materials = item.get("materials")
        if materials is not None:
            if not isinstance(materials, list):
                fail(f"{owner}: materials должен быть списком")
            else:
                keys = []
                for material in materials:
                    if not isinstance(material, dict):
                        fail(f"{owner}: материал должен быть объектом")
                        continue
                    key = str(material.get("key") or "").strip()
                    if not key:
                        fail(f"{owner}: материал без key")
                    keys.append(key)
                    if not title_ru(material):
                        fail(f"{owner}: материал {key or '?'} без русского названия")
                    check_asset(material.get("icon"), f"{owner}#{key}")
                duplicates = [key for key, count in Counter(keys).items() if key and count > 1]
                if duplicates:
                    fail(f"{owner}: дублирующиеся key материалов: {', '.join(duplicates)}")

        dropped_by = item.get("dropped_by")
        if dropped_by:
            if not isinstance(dropped_by, list):
                fail(f"{owner}: dropped_by должен быть списком")
            else:
                missing = [str(enemy_id) for enemy_id in dropped_by if str(enemy_id) not in enemy_ids]
                if missing:
                    fail(f"{owner}: битые ссылки dropped_by: {', '.join(missing)}")

        dropped_by_enemies = item.get("dropped_by_enemies")
        if dropped_by_enemies is not None:
            if not isinstance(dropped_by_enemies, list):
                fail(f"{owner}: dropped_by_enemies должен быть списком")
            else:
                for enemy in dropped_by_enemies:
                    if not isinstance(enemy, dict):
                        fail(f"{owner}: dropped_by_enemies должен содержать объекты")
                        continue
                    enemy_id = str(enemy.get("id") or "").strip()
                    if enemy_id and enemy_id not in enemy_ids:
                        fail(f"{owner}: dropped_by_enemies содержит неизвестного врага {enemy_id}")
                    check_asset(enemy.get("icon"), f"{owner}#enemy:{enemy_id}")


def check_stories(stories: dict[str, dict[str, Any]]) -> None:
    for item_id, story in stories.items():
        owner = f"data/stories/{item_id}.json"
        story_group = str(story.get("story_group") or story.get("category_type") or "").strip()
        if story_group not in KNOWN_STORY_GROUPS:
            fail(f"{owner}: неизвестная группа истории {story_group or '—'}")
        if story_group == "character_stories":
            elements_raw = story.get("elements")
            if isinstance(elements_raw, list):
                elements = [str(value).strip() for value in elements_raw if str(value).strip()]
            else:
                element = str(story.get("element") or "").strip()
                elements = [element] if element else []

            unknown_elements = sorted(value for value in elements if value not in KNOWN_STORY_ELEMENTS)
            if not elements or unknown_elements:
                got = ", ".join(unknown_elements or elements) or "пусто"
                fail(f"{owner}: история персонажа должна иметь element/elements из списка, получено {got}")
            rarity = story.get("rarity")
            if str(rarity) not in {"4", "5"}:
                fail(f"{owner}: история персонажа должна иметь rarity 4 или 5, получено {rarity or 'пусто'}")
        if not localized_text_present(story):
            fail(f"{owner}: история без текста")


def check_enemies(enemies: dict[str, dict[str, Any]]) -> None:
    for item_id, enemy in enemies.items():
        owner = f"data/enemies/{item_id}.json"
        group = str(enemy.get("enemy_group") or "").strip()
        if group not in KNOWN_ENEMY_GROUPS:
            fail(f"{owner}: неизвестный enemy_group {group or 'пусто'}")
        enemy_type = str(enemy.get("enemy_type") or "").strip()
        if enemy_type and enemy_type not in KNOWN_ENEMY_TYPES:
            fail(f"{owner}: неизвестный enemy_type {enemy_type}")
        if not localized_text_present(enemy) and not localized_text_present(enemy, "description"):
            fail(f"{owner}: враг без текста/описания")
        drops = enemy.get("drops")
        if drops is not None and not isinstance(drops, list):
            fail(f"{owner}: drops должен быть списком")
        check_asset(enemy.get("icon"), owner)


def check_summary(indexes: dict[str, list[dict[str, Any]]]) -> None:
    path = DATA_DIR / "archive_summary.json"
    if not path.exists():
        fail("data/archive_summary.json: файл отсутствует")
        return
    summary = read_json(path)
    if not isinstance(summary, dict):
        fail("data/archive_summary.json: ожидается объект")
        return
    for section, items in indexes.items():
        expected = len(items)
        value = summary.get(section)
        if isinstance(value, dict):
            actual = value.get("count") or value.get("total")
        else:
            actual = value
        if actual is not None and actual != expected:
            fail(f"data/archive_summary.json: {section}={actual}, но в индексе {expected}")


def compiled_css_from_sources() -> str | None:
    chunks = [CSS_HEADER.strip()]
    for name in CSS_MODULES:
        path = SRC_CSS_DIR / name
        if not path.exists():
            fail(f"src/css/{name}: CSS-модуль отсутствует")
            return None
        chunks.append(path.read_text(encoding="utf-8").strip())
    return "\n\n".join(chunks).strip() + "\n"


def compiled_js_from_sources() -> str | None:
    chunks = [JS_HEADER.strip(), "(() => {", '  "use strict";']
    for name in JS_MODULES:
        path = SRC_JS_DIR / name
        if not path.exists():
            fail(f"src/js/{name}: JS-модуль отсутствует")
            return None
        module = path.read_text(encoding="utf-8").strip()
        indented = "\n".join(f"  {line}" if line else "" for line in module.splitlines())
        chunks.append(f"  // src/js/{name}\n{indented}")
    chunks.append("})();")
    return "\n\n".join(chunks).strip() + "\n"


def check_generated_js() -> None:
    js = ASSETS_DIR / "js" / "archive.js"
    if not js.exists():
        fail("assets/js/archive.js: итоговый JS отсутствует")
        return

    expected = compiled_js_from_sources()
    if expected is not None:
        actual = js.read_text(encoding="utf-8")
        if actual != expected:
            fail("assets/js/archive.js: файл не совпадает со сборкой из src/js/**")

    source_modules = sorted(str(path.relative_to(SRC_JS_DIR)) for path in SRC_JS_DIR.rglob("*.js")) if SRC_JS_DIR.exists() else []
    if source_modules != sorted(JS_MODULES):
        fail("src/js: набор JS-модулей отличается от ожидаемого списка сборки")


def check_generated_css() -> None:
    css = ASSETS_DIR / "css" / "archive.css"
    if not css.exists():
        fail("assets/css/archive.css: итоговый CSS отсутствует")
        return

    expected = compiled_css_from_sources()
    if expected is not None:
        actual = css.read_text(encoding="utf-8")
        if actual != expected:
            fail("assets/css/archive.css: файл не совпадает со сборкой из src/css/*.css")

    for path in SRC_CSS_DIR.glob("*.css"):
        text = path.read_text(encoding="utf-8")
        if "@media" in text and path.name != "07-responsive.css":
            fail(f"{rel(path)}: @media должен жить только в src/css/07-responsive.css")
        if "!important" in text:
            fail(f"{rel(path)}: найден !important")


    index_html = ROOT / "index.html"
    if index_html.exists():
        index_text = index_html.read_text(encoding="utf-8")
        if "viewport-fit=cover" not in index_text:
            fail("index.html: viewport должен использовать viewport-fit=cover, чтобы iOS не оставлял белые поля в landscape")

    css_text = css.read_text(encoding="utf-8")
    if "!important" in css_text:
        fail("assets/css/archive.css: найден !important")
    defined_vars = set(re.findall(r"--([A-Za-z0-9_-]+)\s*:", css_text))
    used_vars = set(re.findall(r"var\(--([A-Za-z0-9_-]+)", css_text))
    undefined_vars = sorted(used_vars - defined_vars - {"filter-color"})
    if undefined_vars:
        fail("assets/css/archive.css: неизвестные CSS-переменные: " + ", ".join(undefined_vars))
    if "brand-subtitle" not in css_text:
        fail("assets/css/archive.css: подпись под логотипом brand-subtitle должна быть оформлена")
    if "element-icon-stack" in css_text or "element-pill-multi" in css_text or "weapon-rarity-bg" in css_text:
        fail("assets/css/archive.css: остался старый CSS для стопки элементов или оружейных подложек")

    for rarity in ["5", "4", "3", "2", "1"]:
        if f"rarity-bg-{rarity}" not in css_text or f"--rarity-{rarity}-bg" not in css_text:
            fail(f"assets/css/archive.css: отсутствует цветная подложка иконок редкости {rarity}★")

    if "story-detail-icon" not in css_text or "width: 128px" not in css_text:
        fail("assets/css/archive.css: иконка персонажа внутри истории должна быть увеличена отдельным story-detail-icon")
    if "detail-hero-text h1" not in css_text or "text-wrap: balance" not in css_text or "hyphens: none" not in css_text:
        fail("assets/css/archive.css: длинные заголовки в detail-hero должны переноситься по словам без автоматического разрыва слова")
    title_block = re.search(r"\.detail-hero-text h1 \{(?P<body>.*?)\}", css_text, re.S)
    if not title_block or "overflow-wrap: break-word" in title_block.group("body") or "hyphens: auto" in title_block.group("body") or "hyphens: manual" in title_block.group("body"):
        fail("assets/css/archive.css: заголовки detail-hero не должны ломать слова посередине")
    if "story-character-entry-icon" not in css_text or "width: 72px" not in css_text:
        fail("assets/css/archive.css: иконки персонажей в каталоге должны быть увеличены")
    if "story-toolbar .volume-strip" not in css_text or "story-toolbar .volume-scroll button" not in css_text:
        fail("assets/css/archive.css: панель разделов истории должна иметь отдельную безопасную раскладку без вылезания кнопок")

    story_button_block = re.search(r"\.story-toolbar \.volume-scroll button \{(?P<body>.*?)\}", css_text, re.S)
    if not story_button_block:
        fail("assets/css/archive.css: не найден блок кнопок разделов истории")
    else:
        story_button_css = story_button_block.group("body")
        if "white-space: nowrap" not in story_button_css or "flex: 0 0 auto" not in story_button_css:
            fail("assets/css/archive.css: на десктопе длинные названия разделов истории должны переноситься целым чипом")
        forbidden_story_button_css = ["text-overflow: ellipsis", "overflow: hidden", "overflow-wrap: anywhere"]
        for forbidden in forbidden_story_button_css:
            if forbidden in story_button_css:
                fail(f"assets/css/archive.css: осталась старая логика обрезки/грубого переноса кнопок истории: {forbidden}")

    responsive_css = (SRC_CSS_DIR / "07-responsive.css").read_text(encoding="utf-8") if (SRC_CSS_DIR / "07-responsive.css").exists() else ""
    if ".story-toolbar .volume-scroll button" not in responsive_css or "min-width: 0" not in responsive_css or "text-wrap: pretty" not in responsive_css:
        fail("src/css/07-responsive.css: мобильные чипы разделов должны переносить текст внутри чипа без разрыва слов")
    if ".detail-hero" not in responsive_css or "flex-direction: column" not in responsive_css or "align-items: center" not in responsive_css:
        fail("src/css/07-responsive.css: мобильный detail-hero должен ставить иконку над заголовком и центрировать шапку")
    mobile_title_block = re.search(r"\.detail-hero-text h1 \{(?P<body>.*?)\}", responsive_css, re.S)
    if not mobile_title_block or "overflow-wrap: break-word" in mobile_title_block.group("body") or "hyphens: auto" in mobile_title_block.group("body") or "hyphens: manual" in mobile_title_block.group("body"):
        fail("src/css/07-responsive.css: мобильные заголовки не должны переноситься посередине слова")
    if "width: min(54vw, 176px)" not in responsive_css or "width: min(58vw, 192px)" not in responsive_css:
        fail("src/css/07-responsive.css: мобильные иконки в читалке должны быть крупными и ограниченными максимальным размером")
    if "align-items: flex-start" not in css_text or "margin-top: 0.18em" not in css_text:
        fail("assets/css/archive.css: десктопная иконка detail-hero должна выравниваться по русскому заголовку")
    if "minmax(280px" not in css_text or "cols-stories-character" not in css_text:
        fail("assets/css/archive.css: колонка элементов историй персонажей должна быть расширена")

    navigation_css = SRC_CSS_DIR / "03-navigation.css"
    if navigation_css.exists():
        navigation_text = navigation_css.read_text(encoding="utf-8")
        sidebar_block = re.search(r"\.sidebar \{(?P<body>.*?)\}", navigation_text, re.S)
        if not sidebar_block:
            fail("src/css/03-navigation.css: отсутствует основной блок .sidebar")
        else:
            body = sidebar_block.group("body")
            if "overflow: auto" in body or "scrollbar-width" in body or "scrollbar-color" in body:
                fail("src/css/03-navigation.css: десктопное меню не должно иметь внутренний скроллбар")
            if "min-height: calc(100vh - 56px)" not in body or "height: auto" not in body or "overflow: visible" not in body:
                fail("src/css/03-navigation.css: боковое меню должно быть цельной карточкой без внутренней прокрутки")


def check_material_chip_wrapping() -> None:
    catalog_css = SRC_CSS_DIR / "04-catalog.css"
    responsive_css = SRC_CSS_DIR / "07-responsive.css"

    if catalog_css.exists():
        catalog_text = catalog_css.read_text(encoding="utf-8")
        chip_block = re.search(r"\.material-chip \{(?P<body>.*?)\}", catalog_text, re.S)
        if chip_block and "white-space: nowrap" not in chip_block.group("body"):
            fail("src/css/04-catalog.css: material-chip должен переноситься целым чипом, без разрыва текста внутри")
        span_block = re.search(r"\.material-chip span \{(?P<body>.*?)\}", catalog_text, re.S)
        if span_block:
            body = span_block.group("body")
            if "white-space: nowrap" not in body or "text-overflow: ellipsis" not in body:
                fail("src/css/04-catalog.css: длинные названия внутри material-chip должны обрезаться, а не ломать строку")

    if responsive_css.exists():
        responsive_text = responsive_css.read_text(encoding="utf-8")
        block = re.search(r"\.catalog-row\.cols-items-enemy \.material-chip \{(?P<body>.*?)\}", responsive_text, re.S)
        if not block:
            fail("src/css/07-responsive.css: отсутствует desktop-правило для material-chip в каталоге боссов")


def check_common_enemy_layout_guards() -> None:
    catalog_css = SRC_CSS_DIR / "04-catalog.css"
    entries_css = SRC_CSS_DIR / "06-entries.css"
    responsive_css = SRC_CSS_DIR / "07-responsive.css"

    if catalog_css.exists():
        catalog_text = catalog_css.read_text(encoding="utf-8")
        common_block = re.search(r"\.catalog-row\.cols-items-common-enemy \{(?P<body>.*?)\}", catalog_text, re.S)
        if not common_block:
            fail("src/css/04-catalog.css: отсутствует раскладка каталога материалов обычных противников")
        else:
            body = common_block.group("body")
            if "minmax(420px" not in body or "gap: 24px" not in body:
                fail("src/css/04-catalog.css: колонки типа противника и выпадения должны быть отодвинуты от материалов без костылей")

        enemy_block = re.search(r"\.catalog-row\.cols-items-enemy \{(?P<body>.*?)\}", catalog_text, re.S)
        if not enemy_block:
            fail("src/css/04-catalog.css: отсутствует раскладка каталога материалов боссов")
        else:
            body = enemy_block.group("body")
            if "minmax(320px" not in body or "gap: 22px" not in body:
                fail("src/css/04-catalog.css: колонка материалов в каталоге боссов должна быть сдвинута правее общей сеткой")
        if "type-filter-toggle" not in catalog_text:
            fail("src/css/04-catalog.css: общая галочка фильтров должна иметь отдельный стиль")
        if ".catalog-row.cols-stories-character" not in catalog_text or ".type-filter-icon" not in catalog_text or ".element-pill" not in catalog_text:
            fail("src/css/04-catalog.css: для историй персонажей нужны колонки и стили иконок элементов")

        typed_first_block = re.search(r"\.catalog-row\.cols-items-typed\.item > div:first-child \{(?P<body>.*?)\}", catalog_text, re.S)
        if not typed_first_block:
            fail("src/css/04-catalog.css: отсутствует выравнивание первого столбца типовых предметов")
        elif "align-self: center" not in typed_first_block.group("body"):
            fail("src/css/04-catalog.css: название типовых предметов должно выравниваться по центру высокой строки, а не прилипать к верху")

    if entries_css.exists():
        entries_text = entries_css.read_text(encoding="utf-8")
        required = [
            ".dropped-by-grid {",
            "display: grid",
            "align-items: start",
            ".dropped-by-grid.is-single",
            ".dropped-by-grid.is-pair",
            ".dropped-by-grid.is-trio,",
            ".dropped-by-grid.is-cascade",
            "grid-template-columns: repeat(3, minmax(0, 1fr))",
            ".dropped-by-column",
            "align-content: start",
            "a.enemy-loot-chip:hover",
        ]
        for fragment in required:
            if fragment not in entries_text:
                fail(f"src/css/06-entries.css: отсутствует каскадная раскладка блока Выпадает с: {fragment}")
        forbidden = ["is-masonry", "column-count", "column-width", "column-gap"]
        for fragment in forbidden:
            if fragment in entries_text:
                fail(f"src/css/06-entries.css: остался старый код каскадной раскладки: {fragment}")

    if responsive_css.exists():
        responsive_text = responsive_css.read_text(encoding="utf-8")
        for old_selector in (
            "title-icon-start",
            ".catalog-row.item.cols-books .entry-title-cell",
            ".catalog-row.item.cols-artifacts .entry-title-cell",
            ".catalog-row.item.cols-weapons .entry-title-cell",
            ".catalog-row.cols-items-enemy .entry-title-cell",
            ".catalog-row.cols-items-enemy .entry-icon",
        ):
            if old_selector in responsive_text:
                fail("src/css/07-responsive.css: мобильное выравнивание иконок должно быть единым для карточек каталога, без категорийных заплаток")
        catalog_css = SRC_CSS_DIR / "04-catalog.css"
        if catalog_css.exists():
            catalog_text = catalog_css.read_text(encoding="utf-8")
            title_cell = re.search(r"\.entry-title-cell \{(?P<body>.*?)\}", catalog_text, re.S)
            icon_block = re.search(r"\.entry-icon \{(?P<body>.*?)\}", catalog_text, re.S)
            title_block = re.search(r"\.book-title \{(?P<body>.*?)\}", catalog_text, re.S)
            subtitle_block = re.search(r"\.book-subtitle \{(?P<body>.*?)\}", catalog_text, re.S)
            group_title_block = re.search(r"\.group-card-title \{(?P<body>.*?)\}", catalog_text, re.S)
            if not title_cell or "align-items: flex-start" not in title_cell.group("body") or "gap: 11px" not in title_cell.group("body"):
                fail("src/css/04-catalog.css: выравнивание иконки по заголовку должно быть единым базовым правилом для каталога")
            if not icon_block or "--entry-icon-size: 44px" not in icon_block.group("body") or "margin-top: 1px" not in icon_block.group("body"):
                fail("src/css/04-catalog.css: размер и отступ иконок каталога должны задаваться единым базовым правилом")
            story_title_cell = re.search(r"\.catalog-row\.cols-stories-character \.entry-title-cell \{(?P<body>.*?)\}", catalog_text, re.S)
            story_icon_block = re.search(r"\.story-character-entry-icon \{(?P<body>.*?)\}", catalog_text, re.S)
            if not story_title_cell or "align-items: center" not in story_title_cell.group("body"):
                fail("src/css/04-catalog.css: истории персонажей должны явно сохранять центрирование большой портретной иконки")
            if not story_icon_block or "--entry-icon-size: 72px" not in story_icon_block.group("body") or "margin-top: 0" not in story_icon_block.group("body"):
                fail("src/css/04-catalog.css: размер портретных иконок историй персонажей должен задаваться отдельным правилом")
            if not title_block or "line-height: 1.24" not in title_block.group("body"):
                fail("src/css/04-catalog.css: плотность заголовков каталога должна задаваться единым базовым правилом")
            if not subtitle_block or "line-height: 1.22" not in subtitle_block.group("body") or "margin-top: 2px" not in subtitle_block.group("body"):
                fail("src/css/04-catalog.css: плотность подзаголовков каталога должна задаваться единым базовым правилом")
            if not group_title_block or "line-height: 1.13" not in group_title_block.group("body"):
                fail("src/css/04-catalog.css: плотность названий категорий должна задаваться единым базовым правилом")
        for redundant_selector in (
            ".catalog-row.item .entry-title-cell",
            ".catalog-row.item .entry-icon",
            ".catalog-row.item .book-subtitle",
            ".group-card-title",
        ):
            if redundant_selector in responsive_text:
                fail("src/css/07-responsive.css: базовое выравнивание, размер и плотность каталога не должны дублироваться в мобильных заплатках")
        if "html.menu-open," not in responsive_text or "overscroll-behavior: none" not in responsive_text or "touch-action: none" not in responsive_text:
            fail("src/css/07-responsive.css: мобильное меню должно блокировать прокрутку фона, а не только затемнять его")
        mobile_sidebar = re.search(r"@media \(max-width: 1180px\).*?\.archive-layout > \.sidebar,\s*\.sidebar \{(?P<body>.*?)\}", responsive_text, re.S)
        if not mobile_sidebar:
            fail("src/css/07-responsive.css: не найден основной мобильный блок меню")
        else:
            sidebar_body = mobile_sidebar.group("body")
            required_sidebar_fragments = ["top: var(--reader-mobile-bar-top)", "left: 0", "right: 0", "bottom: 0", "width: 100%", "overflow: hidden", "transform: translateY(-100%)"]
            for fragment in required_sidebar_fragments:
                if fragment not in sidebar_body:
                    fail(f"src/css/07-responsive.css: полноэкранное мобильное меню собрано не полностью: {fragment}")
        sidebar_scroll_block = re.search(r"\n  \.sidebar-scroll \{(?P<body>.*?)\}", responsive_text, re.S)
        if not sidebar_scroll_block or "overflow-y: auto" not in sidebar_scroll_block.group("body") or "scrollbar-width: none" not in sidebar_scroll_block.group("body"):
            fail("src/css/07-responsive.css: мобильное меню должно прокручиваться внутри и скрывать системный скролл")
        if "safe-area-inset-left" in (mobile_sidebar.group("body") if mobile_sidebar else ""):
            fail("src/css/07-responsive.css: мобильное меню не должно использовать боковую safe-area как отступ — она оставляет белое поле в landscape")
        if re.search(r"(?<!max-)height: calc\(100dvh - 16px\)", responsive_text) or "bottom: max(12px, env(safe-area-inset-bottom))" in responsive_text:
            fail("src/css/07-responsive.css: старое landscape-меню не должно принудительно растягиваться на всю высоту экрана")
        if "width: 100vw" in responsive_text:
            fail("src/css/07-responsive.css: не должен использоваться width: 100vw — на iOS он может создавать горизонтальный скролл")
        if "calc(100vw - 16px)" in responsive_text:
            fail("src/css/07-responsive.css: landscape-меню не должно снова занимать почти всю ширину экрана")
        forbidden_side_safe_area = [
            "left: max(12px, env(safe-area-inset-left))",
            "padding-left: env(safe-area-inset-left)",
            "padding-right: env(safe-area-inset-right)",
            "margin-left: env(safe-area-inset-left)",
            "margin-right: env(safe-area-inset-right)",
        ]
        for fragment in forbidden_side_safe_area:
            if fragment in responsive_text:
                fail(f"src/css/07-responsive.css: боковая safe-area не должна добавляться как отступ: {fragment}")
        if "width: calc(100% + env(safe-area-inset-left) + env(safe-area-inset-right))" in responsive_text or "margin-left: calc(-1 * env(safe-area-inset-left))" in responsive_text or "margin-right: calc(-1 * env(safe-area-inset-right))" in responsive_text:
            fail("src/css/07-responsive.css: нельзя расширять .app через safe-area — это создаёт горизонтальный скролл на iOS")
        if "html.is-mobile-landscape body::before" not in responsive_text or "left: calc(-1 * env(safe-area-inset-left))" not in responsive_text or "right: calc(-1 * env(safe-area-inset-right))" not in responsive_text:
            fail("src/css/07-responsive.css: iOS landscape должен прокрашивать боковые safe-area через fixed paint-layer, не расширяя layout")
        if "left: calc(12px - env(safe-area-inset-left))" in responsive_text:
            fail("src/css/07-responsive.css: мобильное меню не должно сдвигаться отрицательной safe-area — это может создавать горизонтальный скролл")
        if "@media (max-width: 1180px) and (orientation: landscape)" not in responsive_text or "padding-left: 0;" not in responsive_text or "padding-right: 0;" not in responsive_text or "border-radius: 0;" not in responsive_text:
            fail("src/css/07-responsive.css: в landscape мобильная оболочка должна быть full-bleed, без белых боковых gutters")
        if "html.is-mobile-landscape .app" not in responsive_text or "html.is-mobile-landscape .content" not in responsive_text or "max-width: none;" not in responsive_text:
            fail("src/css/07-responsive.css: для iOS нужен JS-класс is-mobile-landscape, чтобы убирать планшетный max-width даже при нестабильном orientation")
        if ".drawer-backdrop" not in responsive_text or "display: none" not in responsive_text:
            fail("src/css/07-responsive.css: полноэкранное мобильное меню не должно оставлять старую кликабельную подложку поверх навигации")
        if "viewport-fit=cover" not in (ROOT / "index.html").read_text(encoding="utf-8"):
            fail("index.html: нужен viewport-fit=cover для окрашивания боковых safe-area на iOS")
        base_text = (SRC_CSS_DIR / "01-base.css").read_text(encoding="utf-8") if (SRC_CSS_DIR / "01-base.css").exists() else ""
        tokens_text = (SRC_CSS_DIR / "00-tokens.css").read_text(encoding="utf-8") if (SRC_CSS_DIR / "00-tokens.css").exists() else ""
        if "--page-bg-paint" not in tokens_text or "background: var(--page-bg-paint)" not in base_text or "min-height: 100dvh" not in base_text:
            fail("src/css/01-base.css: фон страницы должен прокрашивать весь viewport/safe-area, включая landscape на iOS")
        if "overflow-x: clip" not in responsive_text or ".catalog-page" not in responsive_text or "@supports (overflow: clip)" not in responsive_text:
            fail("src/css/07-responsive.css: мобильная страница каталога должна защищаться от горизонтального скролла")
        if ".search input:focus" not in responsive_text or "inset 0 0 0 2px" not in responsive_text:
            fail("src/css/07-responsive.css: focus-обводка поиска на мобильном не должна раздувать ширину страницы")
        if "font-size: 16px;" not in responsive_text:
            fail("src/css/07-responsive.css: мобильные поля ввода должны быть 16px, чтобы iOS не зумил страницу и не создавал горизонтальный скролл")
        if ".dropped-by-grid.is-cascade" not in responsive_text or "repeat(2, minmax(0, 1fr))" not in responsive_text:
            fail("src/css/07-responsive.css: каскадная раскладка блока Выпадает с должна сжиматься до двух колонок на средних экранах")
        if ".dropped-by-grid.is-pair" not in responsive_text or ".dropped-by-grid.is-trio" not in responsive_text or ".dropped-by-grid.is-cascade" not in responsive_text or "grid-template-columns: minmax(0, 1fr)" not in responsive_text:
            fail("src/css/07-responsive.css: мобильная раскладка блока Выпадает с должна складывать карточки в одну колонку")
        for fragment in ["is-masonry", "column-count", "column-width", "column-gap"]:
            if fragment in responsive_text:
                fail(f"src/css/07-responsive.css: остался старый код каскадной раскладки: {fragment}")


def check_workflow_guards() -> None:
    workflow = ROOT / ".github" / "workflows" / "build-archive.yml"
    if not workflow.exists():
        fail(".github/workflows/build-archive.yml: workflow отсутствует")
        return

    text = workflow.read_text(encoding="utf-8")
    required_fragments = [
        'content/stories/**',
        'src/js/**',
        'tools/build_js.py',
        'assets/icons/**',
        'fetch-depth: 0',
        'git diff --name-only "$before"',
        'python tools/build_js.py',
        'git diff --quiet -- data assets/css/archive.css assets/js/archive.js',
        "grep -Eq '^(assets/js/archive\\.js|assets/icons/)'",
        'python tools/bump_cache_version.py',
        'python tools/check_archive.py',
        'git add data assets/css/archive.css assets/js/archive.js index.html',
    ]
    for fragment in required_fragments:
        if fragment not in text:
            fail(f"{rel(workflow)}: отсутствует защитный фрагмент workflow: {fragment}")


def check_content_structure() -> None:
    if (ASSETS_DIR / "icons" / "hystory").exists():
        fail("assets/icons/hystory: опечатка в названии папки; используйте assets/icons/stories/character")
    if (ASSETS_DIR / "icons" / "history").exists():
        fail("assets/icons/history: папка переименована; используйте assets/icons/stories/character")

    character_story_icon_dir = ASSETS_DIR / "icons" / "stories" / "character"
    if not character_story_icon_dir.exists():
        fail("assets/icons/stories/character: для иконок историй персонажей должна быть отдельная папка")

    content_root = ROOT / "content"
    if not content_root.exists():
        return

    character_story_content_dir = content_root / "stories" / "character"
    if not character_story_content_dir.exists():
        fail("content/stories/character: для историй персонажей должна быть отдельная папка контента")

    content_items = content_root / "items"
    teapot_dir = content_items / "serenitea_pot"
    teyvat_dir = content_items / "teyvat_resources"

    if not teapot_dir.exists():
        fail("content/items/serenitea_pot: для Чайника Безмятежности должна быть отдельная папка контента")

    if teyvat_dir.exists():
        for path in sorted(teyvat_dir.glob("*.md")):
            text = path.read_text(encoding="utf-8")
            if "# item_group: serenitea_pot" in text or "# item_type: teapot" in text:
                fail(f"{rel(path)}: контент Чайника не должен лежать в Ресурсах Тейвата")

    if teapot_dir.exists():
        teapot_types: set[str] = set()
        for path in sorted(teapot_dir.glob("*.md")):
            text = path.read_text(encoding="utf-8")
            if "# item_group: serenitea_pot" not in text:
                fail(f"{rel(path)}: файл в папке Чайника должен иметь item_group: serenitea_pot")
            match = re.search(r"^#\s*item_type\s*:\s*(.+?)\s*$", text, re.MULTILINE)
            if match:
                teapot_types.add(match.group(1).strip())
        required = {"wood", "seed", "misc"}
        missing = required - teapot_types
        if missing:
            fail(f"content/items/serenitea_pot: не найдены типы Чайника: {', '.join(sorted(missing))}")


def check_infrastructure_files() -> None:
    required = [".gitattributes", ".editorconfig", ".gitignore", ".nojekyll"]
    for name in required:
        if not (ROOT / name).exists():
            fail(f"{name}: файл отсутствует")

    nojekyll = ROOT / ".nojekyll"
    if nojekyll.exists() and nojekyll.read_text(encoding="utf-8") not in {"", "\n"}:
        fail(".nojekyll: файл должен быть пустым")

    index = ROOT / "index.html"
    if not index.exists():
        fail("index.html: файл отсутствует")
        return
    text = index.read_text(encoding="utf-8")
    if "публичная база игровых текстов" not in text or "brand-subtitle" not in text:
        fail("index.html: под логотипом должна быть подпись «публичная база игровых текстов»")
    versions = CACHE_RE.findall(text)
    if not versions:
        fail("index.html: не найдены cache-busting версии для CSS/JS")
    elif len(set(versions)) != 1:
        fail(f"index.html: версии cache-bust отличаются: {', '.join(versions)}")


def check_line_endings() -> None:
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.suffix not in TEXT_SUFFIXES and path.name not in TEXT_NAMES:
            continue
        data = path.read_bytes()
        if b"\r\n" in data or b"\r" in data.replace(b"\r\n", b""):
            fail(f"{rel(path)}: найден CRLF/CR, ожидается LF")


def check_interface_regressions() -> None:
    targets = [ROOT / "index.html", ASSETS_DIR / "js" / "archive.js", ASSETS_DIR / "css" / "archive.css"]
    targets.extend(SRC_CSS_DIR.glob("*.css"))
    for path in targets:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if "Томов" in text or "ТОМА" in text:
            fail(f"{rel(path)}: вернулась старая интерфейсная подпись Томов/ТОМА")

    js = ASSETS_DIR / "js" / "archive.js"
    if js.exists():
        text = js.read_text(encoding="utf-8")
        if "const allowLists = options.allowLists === true" not in text:
            fail("assets/js/archive.js: Markdown-списки должны быть opt-in, чтобы не ломать диалоги")
        if "const dialogueMatch = trimmed.match(/^[-–—]" not in text:
            fail("assets/js/archive.js: Markdown-парсер должен сохранять ведущие тире как диалог")
        if "const listMatch = trimmed.match(/^" in text:
            fail("assets/js/archive.js: Markdown-парсер снова превращает дефисные диалоги в списки")
        if "Заметки Лороведьмы" in text and "markdownToHtml(noteText, { allowLists: true })" not in text:
            fail("assets/js/archive.js: заметки должны явно включать Markdown-списки")
        if "const isSinglePartArtifact = parts.length === 1" not in text:
            fail("assets/js/archive.js: одиночные артефакты должны открываться без лишней панели чтения сета")
        if "function versionedAssetPath(path)" not in text:
            fail("assets/js/archive.js: локальные ассеты должны получать cache-busting версию")
        if "versionedAssetPath(icon)" not in text or "versionedAssetPath(material.icon)" not in text:
            fail("assets/js/archive.js: иконки записей и материалов должны версионироваться")
        if "function entryRarityBackgroundClass" not in text or "rarity-bg-${rarity}" not in text:
            fail("assets/js/archive.js: иконки записей с редкостью должны получать класс подложки по редкости")
        if "function renderReaderStickyHead" not in text or "renderReaderStickyHead(book" not in text or "renderReaderStickyHead(artifact" not in text:
            fail("assets/js/archive.js: в читалках должен использоваться общий sticky-топ с иконкой")
        if 'elements.length > 3 ? "is-many"' not in text:
            fail("assets/js/archive.js: множественные элементы персонажа должны получать отдельный класс для аккуратной раскладки")
        if "weaponRarityBackgroundClass" in text or "weapon-rarity-bg" in text:
            fail("assets/js/archive.js: остался старый оружейный код подложек редкости")
        if "renderReaderStickyHead(item" not in text or "entryRarityBackgroundClass(item)" not in text:
            fail("assets/js/archive.js: подложка редкости должна работать в шапке карточки оружия")
        if "const expandedEnemyDescriptionKeys = new Set()" not in text:
            fail("assets/js/archive.js: раскрытый спойлер описания босса должен переживать смену языка")
        if "function rememberEnemyDescriptionState" not in text or "data-description-key" not in text:
            fail("assets/js/archive.js: состояние спойлера описания босса должно быть привязано к записи")
        if "rememberEnemyDescriptionState(panel, !isCollapsed)" not in text:
            fail("assets/js/archive.js: переключение спойлера должно сохранять его состояние")
        if "function renderTextWithAttachedBadge" not in text or 'renderTextWithAttachedBadge(materialTitle(material, "ru")' not in text:
            fail("assets/js/archive.js: бейдж версии должен переноситься вместе с последним словом названия, включая материалы")
        if "function optionsFor(config) {\n  if (isCommonEnemyCatalog(config)) return COMMON_ENEMY_TYPE_FILTERS;" in text:
            fail("assets/js/archive.js: в материалах обычных противников выпадающий фильтр должен быть по региону, а не по типу противника")
        if "function typeFiltersForCurrentCatalog" not in text or "if (isCommonEnemyCatalog(config)) return COMMON_ENEMY_TYPE_FILTERS;" not in text:
            fail("assets/js/archive.js: группы обычных противников должны быть доступны как фильтры-галочки")
        if "Array.from(itemCommonEnemyTypes(item)).some(type => activeTypeSet.has(type))" not in text:
            fail("assets/js/archive.js: фильтры-галочки обычных противников должны работать по пересечению групп")
        if "function droppedByGridClass" not in text or "dropped-by-grid is-single" not in text or "dropped-by-grid is-pair" not in text or "dropped-by-grid is-trio" not in text or "dropped-by-grid is-cascade" not in text:
            fail("assets/js/archive.js: блоки противников должны получать классы для одиночной, парной, тройной и каскадной раскладки")
        if "function distributeDroppedByColumns" not in text or "dropped-by-column" not in text or "index % columns.length" not in text:
            fail("assets/js/archive.js: каскадная раскладка должна распределять 4+ противников по трём явным колонкам")
        if "is-masonry" in text or "column-count" in text:
            fail("assets/js/archive.js: остался старый код каскадной раскладки")
        if 'data-type-filter-toggle' in text or "toggle.indeterminate" in text:
            fail("assets/js/archive.js: в иконковых фильтрах не должно быть общей галочки")
        if '["craft", "Крафт"]' not in text or '["ingredient", "Ингредиенты"]' not in text:
            fail("assets/js/archive.js: в фильтрах ресурсов Тейвата должны быть Крафт и Ингредиенты")
        if '["serenitea_pot", "Чайник Безмятежности"' not in text or '["wood", "Древесина"]' not in text or '["blueprint", "Чертежи"]' not in text or '["seed", "Семена"]' not in text or '["misc", "Прочее"]' not in text:
            fail("assets/js/archive.js: Чайник Безмятежности должен быть отдельной подкатегорией с фильтрами древесины, чертежей, семян и прочего")
        if 'food_potions' in text or 'Еда и зелья' in text or '["teapot", "Чайник"]' in text:
            fail("assets/js/archive.js: старая категория Еда и зелья или старый фильтр Чайник не должны оставаться в клиенте")
        if 'title: "Инвентарь"' not in text:
            fail("assets/js/archive.js: раздел Предметы должен быть переименован в Инвентарь")
        if "function catalogLayoutClass" not in text or "function catalogRowClasses" not in text:
            fail("assets/js/archive.js: классы строк каталога должны формироваться централизованно, без дублирования условий")
        if 'mobileTitleCellAlign' in text or 'title-icon-start' in text:
            fail("assets/js/archive.js: мобильное выравнивание иконок должно быть единым CSS-правилом, без JS-флагов секций")
        if "function renderStoryDetail" not in text or 'id="toggle-story-read-all"' not in text or "data-story-part" not in text:
            fail("assets/js/archive.js: истории должны читаться по разделам и в режиме читать всё подряд")
        if "story-element-list" not in text or "element-icon-stack" in text or "element-pill-multi" in text:
            fail("assets/js/archive.js: несколько элементов персонажа должны выводиться отдельными чипами")
        if "renderTypeFilterRow([...rarityOptions, ...elementOptions]" not in text:
            fail("assets/js/archive.js: иконковые фильтры историй персонажей должны идти в одну строку и начинаться со звёздности")
        if "entryRarityBackgroundClass(item)" not in text or "story-character-entry-icon" not in text:
            fail("assets/js/archive.js: иконки персонажей с редкостью должны быть увеличены и получать фон редкости")
        if '<a class="enemy-loot-chip' not in text or 'routeHash("items", drop.id, group)' not in text:
            fail("assets/js/archive.js: дополнительные ресурсы в карточках противников должны быть кликабельными")
        if '<span class="toolbar-label">Язык</span>\n        <span class="toolbar-label">Язык</span>' in text:
            fail("assets/js/archive.js: не должно быть дублирующихся подписей Язык в переключателях")
        if "function rememberCatalogScrollPosition()" not in text:
            fail("assets/js/archive.js: каталог должен запоминать позицию скролла перед переходом в запись")
        if "function scheduleRouteScroll(routeChanged)" not in text:
            fail("assets/js/archive.js: смена маршрута должна управлять позицией скролла")
        if "markRouteRendered(routeKey, routeChanged)" not in text:
            fail("assets/js/archive.js: после рендера маршрута должна применяться позиция скролла")
        if "state.section = normalizedSection" in text:
            fail("assets/js/archive.js: setRoute не должен менять state до hashchange, иначе ломается сохранение скролла")
        if "function resetHorizontalScroll()" not in text or "window.scrollTo(0, currentY)" not in text:
            fail("assets/js/archive.js: случайный горизонтальный скролл каталога должен сбрасываться без потери вертикальной позиции")
        if "function scheduleViewportCleanup()" not in text or 'window.addEventListener("orientationchange", scheduleViewportCleanup' not in text or 'window.visualViewport?.addEventListener("resize", scheduleViewportCleanup' not in text or "viewportCleanupTimers = [80, 240, 520]" not in text:
            fail("assets/js/archive.js: поворот телефона должен несколько раз сбрасывать горизонтальный скролл, включая visualViewport на iOS")
        if "function updateMobileLandscapeClass()" not in text or "is-mobile-landscape" not in text or "window.visualViewport" not in text or "isTouchLikeViewport()" not in text:
            fail("assets/js/archive.js: телефонный landscape должен определяться через visualViewport и отдельный класс, чтобы убрать белые gutters, даже если CSS orientation сработал нестабильно")
        if "window.scrollTo(0, target.y)" not in text or "catalogScrollPositions.set(currentCatalogScrollKey()" not in text or "x: window.scrollX" in text:
            fail("assets/js/archive.js: сохранение позиции каталога не должно сохранять горизонтальный scrollX")
        if "function openMenu()" not in text or 'document.body.style.position = "fixed"' not in text or 'document.documentElement.classList.add("menu-open")' not in text:
            fail("assets/js/archive.js: мобильное меню должно фиксировать body, чтобы задний фон не прокручивался на iOS")
        if 'drawerBackdrop?.addEventListener("touchmove", event => event.preventDefault(), { passive: false })' not in text:
            fail("assets/js/archive.js: backdrop мобильного меню должен гасить touchmove, иначе фон может прокручиваться")
        if 'let STORIES = []' not in text or 'id: "stories"' not in text or 'STORY_CHILD_GROUPS' not in text:
            fail("assets/js/archive.js: раздел Истории и вложенные подкатегории должны быть подключены в клиенте")
        if 'BACKGROUND_PREFETCH_SECTIONS = new Set(["artifacts", "weapons"])' not in text:
            fail("assets/js/archive.js: тяжёлые индексы items/stories не должны загружаться фоновым prefetch на первом экране")
        if 'function loadStorySearchIndex()' not in text or 'data/stories_search.json' not in text or 'ensureStorySearchIndexForQuery' not in text:
            fail("assets/js/archive.js: полный поиск по историям должен грузиться лениво, а не вместе с каталогом")
        if 'quest_stories' not in text or 'archon_quests' not in text or 'legend_quests' not in text or 'world_quests' not in text:
            fail("assets/js/archive.js: истории заданий должны иметь подкатегории заданий Архонтов, Легенд и мира")
        if 'STORY_CHARACTER_TYPE_FILTERS' not in text or 'ELEMENT_FILTERS' not in text or 'renderStoryElementCell' not in text or 'renderStoryRarityCell' not in text:
            fail("assets/js/archive.js: истории персонажей должны иметь фильтры и колонки элемента/редкости")
        if '${UI_ICON_BASE}/pyro.webp' not in text or 'element:${value}' not in text or 'rarity:5' not in text or 'rarity:4' not in text:
            fail("assets/js/archive.js: фильтры историй персонажей должны использовать актуальные иконки элементов и редкость")
        if 'hasChildGroups(config, state.subsection)' not in text or 'parentGroupFor(config, state.subsection)' not in text:
            fail("assets/js/archive.js: вложенные категории Историй должны открываться отдельным уровнем, а не плоским списком")


def main() -> int:
    check_content_structure()
    check_infrastructure_files()
    check_workflow_guards()
    check_line_endings()
    check_interface_regressions()

    if not DATA_DIR.exists():
        fail("data/: папка не найдена. Сначала запустите tools/build_archive.py")
        indexes = {section: [] for section in SECTIONS}
    else:
        indexes = load_indexes()
        details = check_index_and_details(indexes)
        check_story_search_index(indexes)
        check_books(details.get("books", {}))
        check_artifacts(details.get("artifacts", {}))
        check_weapons(details.get("weapons", {}))
        check_stories(details.get("stories", {}))
        check_enemies(details.get("enemies", {}))
        check_items(details.get("items", {}), details.get("enemies", {}))
        check_summary(indexes)
    check_generated_css()
    check_generated_js()
    check_material_chip_wrapping()
    check_common_enemy_layout_guards()

    if errors:
        print("Проверка архива: найдены ошибки", file=sys.stderr)
        for message in errors:
            print(f"- {message}", file=sys.stderr)
        return 1

    counts = ", ".join(f"{section}: {len(indexes.get(section, []))}" for section in SECTIONS)
    print(f"Проверка архива: OK ({counts})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
